spring.application.name=menu


#contextpath
server.servlet.context-path=/api

#로깅 설정 DEBUG레벨 이상만 보겠다는뜻
logging.level.com.kh.menu=DEBUG

#port
#서버 포트 설정(원래는 8080이 정사임)
server.port=8081

#DataSource
#jdbc:oracle:thin:@localhost:1521:xe여기에서 localhost:1521이부분을 
#서버 아이피로 하면 뭔지 알지 팀프로젝트 할때 알라고
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#여기는 깃에 올라가면 안됨
spring.datasource.username=MENU
spring.datasource.password=MENU

#mybatis
mybatis.mapper-locations=classpath*:/mapper/**/*.xml
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.configuration.map-underscore-to-camel-case=true
#별칭 부여
mybatis.type-aliases-package=com.kh

